### ISSUE TITLE
Very unstable on Ubuntu 22.10, seems to come from the message window

### ISSUE THREAD

**Issue by Kheops97** [conradhuebler/SupraFit#3]
Running the Suprafit 2.0 Appimage on Ubuntu 22.10 and the program is very unstable and crashes often when the message window is open, none of this happens when the message window is closed. 
Data can be imported in from a .tsv file but not copy/pasted in or the program will crash. When data is imported but no model is optimized so the Errors plot is blank, clicking on it will crash the program. Once a model is selected the whole window and application becomes very unstable and unresponsive. Flickers from full-screen to windowed, the hit-box for the buttons de-syncs and so you must click down and left of the button and performance is very slow with lots of lag and jittering.

**Comment by conradhuebler** [comment]
Hey,

thanks for reporting issues with SupraFit. The version 2.0 is quite old and clearly things are not as polished as I would like to have it. However, some of the issues sound a bit unclear to me. Maybe there are some incompatibilities which never appeared before.

In general, would you mind testing a more recent version? While no Appimages are available ( the oldest supported LTS of ubuntu has no Qt 6 ), the linux binaries in the archive should work. If the errors don't appear with the development version, then I would suggest to switch to it.

For the .tsv-file. If you share an example file, I can check it and fix it quite easily.

**Comment by Kheops97** [comment]
Thank you for the reply Conrad!

I am not very well educated with how programs like this are built so I have
downloaded and extracted the SupraFit-nightly-2.5.115-x86_64-Linux.tar.gz
binaries but I can't figure out how to actually run the program from them
and I do not have a compiler installed to compile from the source code.
Could you talk me through how to run the program from extracting the
.tar.gz file please?

Thank you,
Dominic

**Comment by conradhuebler** [comment]
Hey Dominic,

within the archive is a folder called bin. Within this, two binaries (suprafit and suprafit_cli) and a bash script, can be found. Please try if simply clicking (double-clicking) works. The bash scripts changes some path to make sure the distributed Qt6 libs are used. If however, Qt6 is already installed, the binary should work.

If this does not work, try to open the files from within the console and report error messages back.

Btw, which models were you using?

**Comment by Kheops97** [comment]
Hi again,

ahh yes I needed to right click the .bash script and run it as a program
and that started the application. Pasting into a new table from a .tsv or
.csv file now works and selecting the .tsv file works great but not for the
.csv file. The message window also appears to be working fully thankfully
and I also like the new layout for the model selection in the 2.5.115
version!
Unfortunately the program does still close when clicking on an empty chart
but that seems easy enough to avoid.
Thank you for the help, look forward to following the updates!

Dominic

**Comment by conradhuebler** [comment]
Great to hear that thinks work better with the pre-release. Once I commit new things and a new image is built, the fix to the crash in the chart will apply as well.

If you share the csv file, I can have a look at it.

And please report issues etc here (preferable open a new issue) so that I can have a look.

Cheers
Conrad

**Comment by Kheops97** [comment]
Fantastic!

This is the .tsv and .csv files I'm working with, they're proton shifts
from a 1H NMR binding study.

Dominic

**Comment by conradhuebler** [comment]
I suppose, attachments are not working. Would you mind sending me a private mail to the adress listed in any of the source code files eg:
https://github.com/conradhuebler/SupraFit/blob/master/src/global.cpp

**Comment by conradhuebler** [comment]
Latest pre-release build provides an AppImage, a fix for the crash in the error chart and updated tsv and csv import.
https://github.com/conradhuebler/SupraFit/releases/tag/2.5.118
